# Generated by Django 6.0.5 on 2026-06-02 20:18

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SpeakerMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("meeting_stem", models.CharField(max_length=32)),
                ("speaker_id", models.CharField(max_length=32)),
                ("display_name", models.CharField(max_length=128)),
            ],
            options={
                "unique_together": {("meeting_stem", "speaker_id")},
            },
        ),
    ]
