# Generated by Django 6.0.5 on 2026-06-02 21:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web_ui", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("meeting_stem", models.CharField(max_length=32)),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("record", "Record"),
                            ("transcribe", "Transcribe"),
                            ("diarize", "Diarize"),
                            ("merge", "Merge"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("error", models.TextField(blank=True)),
            ],
        ),
    ]
