# Generated by Django 6.0.5 on 2026-06-04 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_ui', '0002_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='language',
            field=models.CharField(blank=True, default='auto', max_length=16),
        ),
    ]
